### PR TITLE
Publish code coverage results

### PR DESCRIPTION
**Pull request by naverus**
Publish code coverage results(Coverage percent and Coverage status) provided by EnForce plugin.
- A new option was added to publish coverage results(default coverage file located on /build/report/coverage.json).
- Current implementation integrates results generated by EnForce with JenkinsChatterPlugin.

More details about how EnForce works, please take a look at:
https://github.com/fundacionjala/enforce-gradle-plugin

### CODE REVIEW

**Comment by superfell** [comment]
Thanks for the patch, i added a few comments to the commit.

**Comment by naverus** [comment]
I fixed your observations and also updated the README.md file.

**Comment by superfell** [comment]
Thanks

**Comment by naverus** [comment]
Great...

**Pull request merged**
